#!/bin/sh

mkdir -p bin

docker build -t examples -f scripts/examples/Dockerfile .
docker run \
  --rm \
  -it \
  -v $(pwd):/workspace \
  -u $(id -u $USER):$(id -g $USER) \
  examples \
  cp decompress /workspace/bin/decompress
